//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnieyeLauncher.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnieyeLauncher.UI.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode button1_ImeMode {
            get {
                object obj = ResourceManager.GetObject("button1.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=266,Y=28}.
        /// </summary>
        public static System.Drawing.Point button1_Location {
            get {
                object obj = ResourceManager.GetObject("button1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding button1_Margin {
            get {
                object obj = ResourceManager.GetObject("button1.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=33}.
        /// </summary>
        public static System.Drawing.Size button1_Size {
            get {
                object obj = ResourceManager.GetObject("button1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int button1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("button1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonAddStartupMenu_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonAddStartupMenu.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=8,Y=28}.
        /// </summary>
        public static System.Drawing.Point buttonAddStartupMenu_Location {
            get {
                object obj = ResourceManager.GetObject("buttonAddStartupMenu.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonAddStartupMenu_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonAddStartupMenu.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=33}.
        /// </summary>
        public static System.Drawing.Size buttonAddStartupMenu_Size {
            get {
                object obj = ResourceManager.GetObject("buttonAddStartupMenu.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonAddStartupMenu_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonAddStartupMenu.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string buttonAddStartupMenu_Text {
            get {
                return ResourceManager.GetString("buttonAddStartupMenu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonBackup_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonBackup.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=524,Y=7}.
        /// </summary>
        public static System.Drawing.Point buttonBackup_Location {
            get {
                object obj = ResourceManager.GetObject("buttonBackup.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonBackup_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonBackup.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=91}.
        /// </summary>
        public static System.Drawing.Size buttonBackup_Size {
            get {
                object obj = ResourceManager.GetObject("buttonBackup.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonBackup_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonBackup.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string buttonBackup_Text {
            get {
                return ResourceManager.GetString("buttonBackup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=252,Y=50}.
        /// </summary>
        public static System.Drawing.Point buttonKill_Location {
            get {
                object obj = ResourceManager.GetObject("buttonKill.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonKill_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonKill.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=58, Height=48}.
        /// </summary>
        public static System.Drawing.Size buttonKill_Size {
            get {
                object obj = ResourceManager.GetObject("buttonKill.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonKill_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonKill.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string buttonKill_Text {
            get {
                return ResourceManager.GetString("buttonKill.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=16,Y=50}.
        /// </summary>
        public static System.Drawing.Point buttonLaunch_Location {
            get {
                object obj = ResourceManager.GetObject("buttonLaunch.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonLaunch_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonLaunch.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=226, Height=48}.
        /// </summary>
        public static System.Drawing.Size buttonLaunch_Size {
            get {
                object obj = ResourceManager.GetObject("buttonLaunch.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonLaunch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonLaunch.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string buttonLaunch_Text {
            get {
                return ResourceManager.GetString("buttonLaunch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImeMode similar to NoControl.
        /// </summary>
        public static System.Windows.Forms.ImeMode buttonRemoveStartupMenu_ImeMode {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveStartupMenu.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=137,Y=28}.
        /// </summary>
        public static System.Drawing.Point buttonRemoveStartupMenu_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveStartupMenu.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonRemoveStartupMenu_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveStartupMenu.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=119, Height=33}.
        /// </summary>
        public static System.Drawing.Size buttonRemoveStartupMenu_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveStartupMenu.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonRemoveStartupMenu_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRemoveStartupMenu.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string buttonRemoveStartupMenu_Text {
            get {
                return ResourceManager.GetString("buttonRemoveStartupMenu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonRestore_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonRestore.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=652,Y=7}.
        /// </summary>
        public static System.Drawing.Point buttonRestore_Location {
            get {
                object obj = ResourceManager.GetObject("buttonRestore.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonRestore_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonRestore.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=118, Height=91}.
        /// </summary>
        public static System.Drawing.Size buttonRestore_Size {
            get {
                object obj = ResourceManager.GetObject("buttonRestore.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonRestore_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonRestore.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string buttonRestore_Text {
            get {
                return ResourceManager.GetString("buttonRestore.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles buttonSettingSave_Anchor {
            get {
                object obj = ResourceManager.GetObject("buttonSettingSave.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=674,Y=301}.
        /// </summary>
        public static System.Drawing.Point buttonSettingSave_Location {
            get {
                object obj = ResourceManager.GetObject("buttonSettingSave.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=5,Top=7,Right=5,Bottom=7}.
        /// </summary>
        public static System.Windows.Forms.Padding buttonSettingSave_Margin {
            get {
                object obj = ResourceManager.GetObject("buttonSettingSave.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=105, Height=33}.
        /// </summary>
        public static System.Drawing.Size buttonSettingSave_Size {
            get {
                object obj = ResourceManager.GetObject("buttonSettingSave.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int buttonSettingSave_TabIndex {
            get {
                object obj = ResourceManager.GetObject("buttonSettingSave.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string buttonSettingSave_Text {
            get {
                return ResourceManager.GetString("buttonSettingSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=16,Y=7}.
        /// </summary>
        public static System.Drawing.Point comboBoxExcutable_Location {
            get {
                object obj = ResourceManager.GetObject("comboBoxExcutable.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=294, Height=33}.
        /// </summary>
        public static System.Drawing.Size comboBoxExcutable_Size {
            get {
                object obj = ResourceManager.GetObject("comboBoxExcutable.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int comboBoxExcutable_TabIndex {
            get {
                object obj = ResourceManager.GetObject("comboBoxExcutable.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=147, Height=70}.
        /// </summary>
        public static System.Drawing.Size contextMenuStrip_Size {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=289,Y=17}.
        /// </summary>
        public static System.Drawing.Point contextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size exitToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("exitToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exitToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("exitToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=261}.
        /// </summary>
        public static System.Drawing.Point groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=405, Height=73}.
        /// </summary>
        public static System.Drawing.Size groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Menu.
        /// </summary>
        public static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon notifyIcon_Icon {
            get {
                object obj = ResourceManager.GetObject("notifyIcon.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point notifyIcon_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("notifyIcon.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool notifyIcon_Visible {
            get {
                object obj = ResourceManager.GetObject("notifyIcon.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        public static System.Windows.Forms.DockStyle panel1_Dock {
            get {
                object obj = ResourceManager.GetObject("panel1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point panel1_Location {
            get {
                object obj = ResourceManager.GetObject("panel1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=784, Height=110}.
        /// </summary>
        public static System.Drawing.Size panel1_Size {
            get {
                object obj = ResourceManager.GetObject("panel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int panel1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panel1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        public static System.Windows.Forms.DockStyle panelSetting_Dock {
            get {
                object obj = ResourceManager.GetObject("panelSetting.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Font similar to [Font: Name=Malgun Gothic, Size=10, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        public static System.Drawing.Font panelSetting_Font {
            get {
                object obj = ResourceManager.GetObject("panelSetting.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=110}.
        /// </summary>
        public static System.Drawing.Point panelSetting_Location {
            get {
                object obj = ResourceManager.GetObject("panelSetting.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=784, Height=343}.
        /// </summary>
        public static System.Drawing.Size panelSetting_Size {
            get {
                object obj = ResourceManager.GetObject("panelSetting.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int panelSetting_TabIndex {
            get {
                object obj = ResourceManager.GetObject("panelSetting.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        public static System.Windows.Forms.DockStyle propertyGrid1_Dock {
            get {
                object obj = ResourceManager.GetObject("propertyGrid1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point propertyGrid1_Location {
            get {
                object obj = ResourceManager.GetObject("propertyGrid1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=784, Height=255}.
        /// </summary>
        public static System.Drawing.Size propertyGrid1_Size {
            get {
                object obj = ResourceManager.GetObject("propertyGrid1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int propertyGrid1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("propertyGrid1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size settingToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("settingToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string settingToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("settingToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=452}.
        /// </summary>
        public static System.Drawing.Point statusStrip_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusStrip_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("statusStrip.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=784, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusStrip_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int statusStrip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statusStrip1.
        /// </summary>
        public static string statusStrip_Text {
            get {
                return ResourceManager.GetString("statusStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=440,Y=17}.
        /// </summary>
        public static System.Drawing.Point statusStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        public static bool versionStringToolStripMenuItem_Enabled {
            get {
                object obj = ResourceManager.GetObject("versionStringToolStripMenuItem.Enabled", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=146, Height=22}.
        /// </summary>
        public static System.Drawing.Size versionStringToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("versionStringToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionString.
        /// </summary>
        public static string versionStringToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("versionStringToolStripMenuItem.Text", resourceCulture);
            }
        }
    }
}
